/* shared.js — dipakai bersama index.html (game) dan admin.html (panel admin).

   Script KLASIK, bukan ES module: agar index.html tetap jalan saat dibuka via
   file:// (modul ditolak CORS di file://). Harus dimuat SEBELUM script inline
   tiap halaman.

   Isi: kunci localStorage, konfigurasi merek (white-label), bank soal, dan
   deteksi kemampuan server. Kedua halaman WAJIB memakai definisi di sini — kalau
   diduplikat, konten yang diedit admin akan menyimpang dari yang dipakai game. */

/* ==================================================== helpers */
function $(id){return document.getElementById(id);}
function showFeedback(msg,good){
  var f=$('feedback');if(!f)return;
  f.textContent=msg;f.className='feedback show '+(good?'good':'bad');
  clearTimeout(f._t);f._t=setTimeout(function(){f.classList.remove('show');},1300);
}

/* ==================================================== config + white-label */
const LS_CFG='bic_brand_v1',LS_PROG='bic_progress_v2',LS_PLAYER='bic_player_v1',
      LS_ROOM='bic_room_v1',LS_BOARD='bic_board_v1',LS_CONTENT='bic_content_v1',LS_ADMINKEY='bic_adminkey_v1';
const DEFAULT_CFG={brandL1:'Bahasa Indonesia',brandL2:'Ceria',brandEmoji:'🎈',mascot:'⭐',logo:'',
  subtitle:'Bermain sambil belajar Bahasa Indonesia!',footer:'Dibuat dengan ❤ untuk belajar Bahasa Indonesia',
  accent:'#0CA678',adminPass:'admin123'};
const PRESET_COLORS=['#0CA678','#FF6B6B','#F59F00','#37B24D','#1C7ED6','#AE3EC9','#E8590C','#2f2f45'];
let CFG=loadCfg(),isAdmin=false;
function loadCfg(){try{return {...DEFAULT_CFG,...(JSON.parse(localStorage.getItem(LS_CFG)||'{}'))};}catch(e){return {...DEFAULT_CFG};}}
function saveCfg(){try{localStorage.setItem(LS_CFG,JSON.stringify(CFG));}catch(e){}}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function contrast(hex){const h=hex.replace('#','');if(h.length<6)return '#fff';const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16);return (r*299+g*587+b*114)/1000>150?'#2f2f45':'#ffffff';}
function applyBranding(){
  document.documentElement.style.setProperty('--accent',CFG.accent);
  document.documentElement.style.setProperty('--accent-ink',contrast(CFG.accent));
  const tc=document.querySelector('meta[name=theme-color]');if(tc)tc.content=CFG.accent;
  document.title=(CFG.brandL1+' '+CFG.brandL2).trim();
  if(!$('brandBox'))return;
  if(CFG.logo){$('brandBox').innerHTML=`<img class="brandlogo" src="${esc(CFG.logo)}" alt="logo" onerror="this.replaceWith(document.createTextNode('${esc((CFG.brandL1+' '+CFG.brandL2).trim())}'))">`;}
  else{$('brandBox').innerHTML=`${esc(CFG.brandL1)} ${esc(CFG.brandL2)} ${esc(CFG.brandEmoji)}<small>${esc(CFG.subtitle)}</small>`;}
  var gm=$('gateMascot');if(gm)gm.textContent=CFG.mascot;
  var ft=$('footerText');if(ft)ft.textContent=CFG.footer;
}

/* ==================================================== data (mutable for content override) */
/* ==================================================== data (mutable for content override) */
const C={coral:['#FF6B6B','#FFE3E3'],amber:['#F59F00','#FFF3BF'],green:['#37B24D','#D3F9D8'],blue:['#1C7ED6','#D0EBFF'],purple:['#AE3EC9','#F3D9FA'],teal:['#0CA678','#C3FAE8']};
let HURUF=[['🍎','apel'],['⚽','bola'],['🐱','kucing'],['🐟','ikan'],['🌂','payung'],['🐘','gajah'],['🏠','rumah'],['🍞','roti'],['👟','sepatu'],['🐔','ayam'],['🥛','susu'],['📚','buku'],['🌙','bulan'],['⭐','bintang'],['🚗','mobil'],['🍌','pisang'],['🐸','kodok'],['🌻','bunga'],['🧀','keju'],['🥕','wortel'],['🐝','lebah'],['🍉','semangka'],['🚲','sepeda'],['🎈','balon'],['🐧','pinguin'],['🌵','kaktus'],['🍇','anggur'],['🐢','kura'],['🧦','kaus'],['🕯️','lilin'],
/* kata ≥7 huruf — menjaga level Mahir (band [7,99]) punya cukup soal sendiri */
['🦒','jerapah'],['🌞','matahari'],['🏫','sekolah'],['🌈','pelangi'],['🐅','harimau'],['🦀','kepiting'],['✈️','pesawat'],['🎺','terompet'],['🪁','layangan'],['👓','kacamata'],['👑','mahkota'],['🪟','jendela'],['🥔','kentang'],['🚁','helikopter']];
let SUKU=[['⚽','bola',['bo','la']],['👀','mata',['ma','ta']],['📚','buku',['bu','ku']],['🍞','roti',['ro','ti']],['🐄','sapi',['sa','pi']],['🎩','topi',['to','pi']],['🍌','pisang',['pi','sang']],['🌻','bunga',['bu','nga']],['🚂','kereta',['ke','re','ta']],['🚲','sepeda',['se','pe','da']],['🌈','pelangi',['pe','la','ngi']],['🥥','kelapa',['ke','la','pa']],['🐘','gajah',['ga','jah']],['🍇','anggur',['ang','gur']],['🌞','matahari',['ma','ta','ha','ri']],['🧹','sapu',['sa','pu']],['🦋','kupu',['ku','pu']],['🐊','buaya',['bu','a','ya']],['🍉','semangka',['se','mang','ka']],['🏫','sekolah',['se','ko','lah']],['🌴','pohon',['po','hon']],['🚪','pintu',['pin','tu']],['🪑','kursi',['kur','si']],['🖊️','pena',['pe','na']],['🐜','semut',['se','mut']],['🏔️','gunung',['gu','nung']],['🍚','nasi',['na','si']],['🥁','gendang',['gen','dang']],['🐓','ayam',['a','yam']],['🌧️','hujan',['hu','jan']],
/* kata ≥7 huruf — menjaga level Mahir (band [7,99]) punya cukup soal sendiri */
['🦒','jerapah',['je','ra','pah']],['🐅','harimau',['ha','ri','mau']],['🦀','kepiting',['ke','pi','ting']],['✈️','pesawat',['pe','sa','wat']],['🎺','terompet',['te','rom','pet']],['👓','kacamata',['ka','ca','ma','ta']],['👑','mahkota',['mah','ko','ta']],['🪟','jendela',['jen','de','la']],['🥔','kentang',['ken','tang']],['🪁','layangan',['la','ya','ngan']],['🚁','helikopter',['he','li','kop','ter']]];
let KALIMAT=['Ibu memasak nasi','Adik minum susu','Budi bermain bola','Kucing makan ikan','Ayah membaca koran','Saya suka membaca buku','Rina pergi ke sekolah','Kakak menulis surat','Nenek menyiram bunga','Kami belajar bersama','Burung terbang tinggi','Ikan berenang di kolam','Petani menanam padi','Guru mengajar murid','Anjing menggonggong keras','Matahari bersinar terang','Hujan turun sore hari','Kakek memancing ikan','Ibu membeli sayur segar','Adik bermain di taman kota','Kucing tidur di sofa','Ibu menyapu lantai rumah','Adik menggambar pemandangan indah','Kami bermain di halaman','Ayah mencuci mobil biru','Nenek memasak sayur bayam','Murid membaca buku cerita','Kakak menyanyi lagu daerah','Paman memelihara ayam kampung','Kita menjaga kebersihan kelas'];
let TANDA=[['Siapa namamu','?'],['Saya suka membaca','.'],['Wah, indah sekali','!'],['Di mana rumahmu','?'],['Ayo cuci tangan','!'],['Hari ini hujan','.'],['Kapan kamu ulang tahun','?'],['Hore, kita menang','!'],['Adik tidur siang','.'],['Mengapa kamu terlambat','?'],['Selamat pagi, teman-teman','!'],['Berapa umurmu sekarang','?'],['Kucingku sangat lucu','.'],['Awas, ada mobil','!'],['Bolehkah aku ikut','?'],['Ibu sedang memasak','.'],['Siapa yang datang','?'],['Betapa lucunya kucing itu','!'],['Aku suka warna biru','.'],['Ke mana kamu pergi','?'],['Hati-hati di jalan','!'],['Adik sedang belajar','.'],['Apa nama binatang itu','?'],['Wow, hebat sekali','!'],['Kami tinggal di desa','.'],['Mengapa kamu menangis','?'],['Ayo kita berangkat','!'],['Bunga itu sangat harum','.'],['Berapa harga buku ini','?'],['Jangan lupa berdoa','!']];
let ANTONIM=[['besar','kecil'],['panjang','pendek'],['terang','gelap'],['rajin','malas'],['tinggi','rendah'],['cepat','lambat'],['panas','dingin'],['ramai','sepi'],['berani','takut'],['bersih','kotor'],['tua','muda'],['kaya','miskin'],['baru','lama'],['manis','pahit'],['naik','turun'],['buka','tutup'],['siang','malam'],['depan','belakang'],['kuat','lemah'],['banyak','sedikit'],['jauh','dekat'],['tebal','tipis'],['keras','lunak'],['basah','kering'],['penuh','kosong'],['mudah','sulit'],['datang','pergi'],['menang','kalah'],['awal','akhir'],['luas','sempit']];
let BACA=[
  {p:'Sinta memelihara kucing bernama Momo. Setiap pagi Sinta memberi Momo makan ikan. Momo suka bermain bola benang di halaman.',q:[['Siapa nama kucing Sinta?',['Momo','Sinta','Ikan'],0],['Apa makanan Momo setiap pagi?',['Roti','Ikan','Nasi'],1],['Di mana Momo suka bermain?',['Di kamar','Di sekolah','Di halaman'],2]]},
  {p:'Taman kota ramai pada hari Minggu. Banyak anak bermain layang-layang di lapangan. Pedagang es krim berkeliling dengan sepedanya.',q:[['Kapan taman kota menjadi ramai?',['Hari Senin','Hari Minggu','Malam hari'],1],['Apa yang dimainkan anak-anak?',['Layang-layang','Bola','Boneka'],0],['Siapa yang berkeliling dengan sepeda?',['Guru','Polisi','Pedagang es krim'],2]]},
  {p:'Seekor semut hanyut di sungai. Merpati menjatuhkan daun untuk menolongnya. Semut pun selamat dan berterima kasih kepada merpati.',q:[['Siapa yang menolong semut?',['Merpati','Kerbau','Kancil'],0],['Di mana semut hanyut?',['Di laut','Di sungai','Di kolam'],1]]},
  {p:'Rina bangun pagi-pagi. Ia mandi lalu sarapan roti dan susu. Rina berangkat ke sekolah dengan hati senang.',q:[['Apa sarapan Rina?',['Nasi goreng','Roti dan susu','Buah'],1],['Bagaimana perasaan Rina?',['Sedih','Marah','Senang'],2]]},
  {p:'Pak Tani menanam jagung di ladang. Setiap hari ia menyiram tanamannya. Setelah beberapa bulan, jagung pun siap dipanen.',q:[['Apa yang ditanam Pak Tani?',['Padi','Jagung','Cabai'],1],['Apa yang dilakukan setiap hari?',['Menyiram','Memupuk','Memanen'],0],['Kapan jagung dipanen?',['Esok hari','Setelah beberapa bulan','Minggu depan'],1]]},
  {p:'Dodi menanam bunga matahari di halaman rumah. Ia menyiramnya setiap sore. Bunga itu tumbuh tinggi dan mekar berwarna kuning.',q:[['Apa yang ditanam Dodi?',['Bunga matahari','Bunga mawar','Pohon mangga'],0],['Kapan Dodi menyiram bunganya?',['Setiap pagi','Setiap malam','Setiap sore'],2],['Apa warna bunga itu?',['Merah','Kuning','Biru'],1]]},
  {p:'Setiap hari Minggu, Andi membantu ayah mencuci mobil. Andi menyiapkan ember dan sabun. Setelah selesai, mobil menjadi bersih dan mengkilap.',q:[['Kapan Andi membantu ayah?',['Hari Sabtu','Hari Minggu','Hari Senin'],1],['Apa yang disiapkan Andi?',['Ember dan sabun','Sapu dan pel','Pensil dan buku'],0],['Bagaimana mobil setelah dicuci?',['Kotor','Basah saja','Bersih dan mengkilap'],2]]},
  {p:'Bu Rina adalah seorang guru. Ia mengajar di kelas satu. Murid-murid sangat menyayangi Bu Rina karena ia sabar dan ramah.',q:[['Apa pekerjaan Bu Rina?',['Dokter','Guru','Petani'],1],['Bu Rina mengajar di kelas berapa?',['Kelas satu','Kelas dua','Kelas tiga'],0],['Mengapa murid menyayangi Bu Rina?',['Karena galak','Karena sabar dan ramah','Karena kaya'],1]]},
  {p:'Kelinci dan kura-kura berlomba lari. Kelinci berlari cepat lalu tertidur di tengah jalan. Kura-kura berjalan pelan tanpa henti dan akhirnya menang.',q:[['Siapa yang berlomba?',['Kelinci dan kura-kura','Kucing dan tikus','Semut dan gajah'],0],['Mengapa kelinci kalah?',['Ia tersesat','Ia tertidur','Ia sakit'],1],['Siapa pemenangnya?',['Kelinci','Kura-kura','Keduanya'],1]]},
  {p:'Di pagi hari, Nisa membantu ibu menyapu lantai. Setelah itu ia sarapan bubur ayam. Nisa lalu berangkat ke sekolah naik sepeda.',q:[['Apa yang dibantu Nisa?',['Menyapu lantai','Mencuci piring','Memasak nasi'],0],['Apa sarapan Nisa?',['Roti','Bubur ayam','Mi goreng'],1],['Naik apa Nisa ke sekolah?',['Bus','Sepeda','Jalan kaki'],1]]},
  {p:'Hutan adalah rumah bagi banyak binatang. Pohon-pohon di hutan menghasilkan udara bersih. Kita harus menjaga hutan agar tetap lestari.',q:[['Hutan adalah rumah bagi siapa?',['Banyak binatang','Manusia saja','Tidak ada'],0],['Apa yang dihasilkan pohon di hutan?',['Udara bersih','Air keruh','Asap'],0]]}
];
let SINONIM=[['pintar','pandai'],['senang','gembira'],['hewan','binatang'],['bunga','kembang'],['baju','pakaian'],['lelah','capai'],['cantik','elok'],['cepat','laju'],['bohong','dusta'],['bertemu','berjumpa'],['pandang','lihat'],['besar','agung'],['sedih','duka'],['marah','geram'],['takut','ngeri'],['kecil','mungil'],['indah','permai'],['kuat','perkasa'],['guru','pengajar'],['murid','pelajar'],['teman','kawan'],['ayah','bapak'],['ibu','bunda'],['wajah','muka'],['suara','bunyi'],['hutan','rimba'],['sungai','kali'],['kampung','desa'],['lucu','jenaka'],['sopan','santun']];
let WARNA=[['merah','#e03131'],['biru','#1c7ed6'],['kuning','#f2c200'],['hijau','#2f9e44'],['ungu','#ae3ec9'],['oranye','#e8590c'],['merah muda','#f06595'],['cokelat','#8a5a2b'],['hitam','#2f2f45'],['putih','#dee2e6'],['abu-abu','#868e96'],['biru muda','#74c0fc'],['biru tua','#1864ab'],['hijau muda','#8ce99a'],['hijau tua','#2b8a3e'],['merah tua','#a61e1e'],['kuning muda','#ffe066'],['ungu muda','#d0bfff'],['krem','#f5e6c8'],['emas','#d4af37'],['perak','#c0c4c8'],['tosca','#0ca678'],['nila','#3b3bb3'],['jingga','#fd7e14'],['lembayung','#b197fc'],['magenta','#d6336c'],['zaitun','#6f7a1f'],['marun','#7b1e3a'],['biru langit','#a5d8ff'],['hijau lumut','#5c7a29']];
let KATADEPAN=[['Buku itu ada ___ atas meja','di'],['Ayah pergi ___ kantor','ke'],['Ia pulang ___ sekolah','dari'],['Kucing tidur ___ bawah kursi','di'],['Kami berlibur ___ pantai','ke'],['Adik meminta uang ___ ibu','dari'],['Burung hinggap ___ dahan','di'],['Hadiah ini ___ nenek','dari'],['Mereka berjalan ___ pasar untuk berbelanja','ke'],['Lukisan tergantung ___ dinding','di'],['Kereta berangkat ___ stasiun menuju Bandung','dari'],['Kita menabung ___ bank','di'],['Kami belajar ___ dalam kelas','di'],['Ibu berangkat ___ pasar pagi ini','ke'],['Ayah baru pulang ___ kantor','dari'],['Sepatu itu tersimpan ___ rak','di'],['Adik berlari ___ arah taman','ke'],['Kue ini dibuat ___ tepung beras','dari'],['Bunga mawar tumbuh ___ taman','di'],['Kami akan pindah ___ kota lain','ke'],['Ia berasal ___ Surabaya','dari'],['Buku itu tergeletak ___ lantai','di'],['Mereka naik ___ puncak bukit','ke'],['Ibu menerima surat ___ paman','dari'],['Kucing bersembunyi ___ kolong meja','di'],['Kakak mengantar adik ___ sekolah','ke'],['Susu ini terbuat ___ kedelai','dari'],['Kami berteduh ___ bawah pohon','di'],['Kami berkunjung ___ rumah nenek','ke'],['Hadiah ini kudapat ___ ayah','dari']];
let BEDA=[{g:['sapi','ayam','kambing'],odd:'mobil'},{g:['merah','biru','hijau'],odd:'meja'},{g:['apel','jeruk','pisang'],odd:'kucing'},{g:['guru','dokter','petani'],odd:'bunga'},{g:['satu','dua','tiga'],odd:'baju'},{g:['mata','hidung','telinga'],odd:'sepatu'},{g:['pagi','siang','malam'],odd:'meja'},{g:['bus','kereta','pesawat'],odd:'roti'},{g:['ibu','ayah','kakak'],odd:'kursi'},{g:['bola','boneka','balon'],odd:'nasi'},{g:['kursi','meja','lemari'],odd:'apel'},{g:['pensil','pulpen','penghapus'],odd:'ayam'},{g:['mangga','durian','rambutan'],odd:'sepeda'},{g:['hujan','angin','petir'],odd:'buku'},{g:['gitar','piano','drum'],odd:'jeruk'},{g:['dokter','perawat','bidan'],odd:'jagung'},{g:['senin','selasa','rabu'],odd:'merah'},{g:['sepatu','kaus kaki','topi'],odd:'ikan'},{g:['padi','jagung','kedelai'],odd:'kucing'},{g:['laut','sungai','danau'],odd:'kursi'},{g:['singa','harimau','beruang'],odd:'sepatu'},{g:['nasi','roti','mi'],odd:'batu'},{g:['mata','tangan','kaki'],odd:'awan'},{g:['gelas','piring','sendok'],odd:'burung'},{g:['bunga','daun','akar'],odd:'mobil'},{g:['januari','februari','maret'],odd:'sabtu'},{g:['bulat','segitiga','persegi'],odd:'manis'},{g:['manis','asin','pahit'],odd:'bulat'},{g:['pesawat','helikopter','balon udara'],odd:'kapal selam'},{g:['guru','murid','sekolah'],odd:'pisang'}];
/* [baku, tidak baku] — ejaan sesuai KBBI. Level memakai panjang kata baku. */
let BAKU=[['izin','ijin'],['rapi','rapih'],['napas','nafas'],['utang','hutang'],['paham','faham'],['cabai','cabe'],['antre','antri'],['hafal','hapal'],['zaman','jaman'],['sopir','supir'],['atlet','atlit'],['daftar','daptar'],['sistem','sistim'],['risiko','resiko'],['teknik','tehnik'],['apotek','apotik'],['jadwal','jadual'],['peduli','perduli'],['ijazah','ijasah'],['praktik','praktek'],['nasihat','nasehat'],['telepon','telpon'],['sekadar','sekedar'],['hakikat','hakekat'],['konkret','konkrit'],['silakan','silahkan'],['kategori','katagori'],['provinsi','propinsi'],['terampil','trampil'],['kualitas','kwalitas']];
/* [kalimat dengan ___, kata tanya] — pilihan diambil dari KATA_TANYA di bawah. */
let KATATANYA=[['___ nama ibumu?','siapa'],['___ kamu menangis?','mengapa'],['___ rumahmu?','di mana'],['___ kamu berangkat ke sekolah?','kapan'],['___ yang kamu bawa di tas?','apa'],['___ cara membuat layang-layang?','bagaimana'],['___ harga buku ini?','berapa'],['___ yang menolong semut itu?','siapa'],['___ kamu terlambat hari ini?','mengapa'],['___ kita menyimpan sepatu?','di mana'],['___ hari ulang tahunmu?','kapan'],['___ makanan kesukaanmu?','apa'],['___ keadaan nenek sekarang?','bagaimana'],['___ jumlah murid di kelasmu?','berapa'],['___ yang mengajar di kelas satu?','siapa'],['___ daun itu berwarna hijau?','mengapa'],['___ kita bisa membeli buku tulis?','di mana'],['___ upacara bendera dimulai?','kapan'],['___ nama binatang berbelalai panjang?','apa'],['___ rasanya buah durian?','bagaimana'],['___ umurmu tahun ini?','berapa'],['___ pemenang lomba lari itu?','siapa'],['___ ikan tidak bisa hidup di darat?','mengapa'],['___ ayah menyimpan kunci motor?','di mana'],['___ kita berlibur ke rumah nenek?','kapan'],['___ warna kesukaanmu?','apa'],['___ cara mencuci tangan yang benar?','bagaimana'],['___ kaki seekor kucing?','berapa'],['___ yang membuang sampah di sini?','siapa'],['___ kita harus rajin belajar?','mengapa']];
const KATA_TANYA=['apa','siapa','di mana','kapan','mengapa','bagaimana','berapa'];
/* [kalimat dengan ___, bentuk berimbuhan yang benar, daftar pengecoh] */
let IMBUHAN=[['Ibu ___ koran di teras.','membaca',['dibaca','pembaca','terbaca']],['Adik ___ bola ke gawang.','menendang',['ditendang','penendang','tertendang']],['Ayah ___ mobil setiap Minggu.','mencuci',['dicuci','pencuci','tercuci']],['Baju kotor itu ___ oleh kakak.','dicuci',['mencuci','pencuci','pencucian']],['Rina ___ surat untuk nenek.','menulis',['ditulis','penulis','tertulis']],['Namaku sudah ___ di papan tulis.','tertulis',['menulis','penulis','tulisan']],['Kami ___ di lapangan sekolah.','bermain',['dimainkan','permainan','pemain']],['Andi seorang ___ bulu tangkis.','pemain',['bermain','dimainkan','permainan']],['Bu Rina ___ murid kelas satu.','mengajar',['diajar','pengajar','pelajaran']],['Kami ___ oleh guru yang sabar.','diajar',['mengajar','pengajar','ajaran']],['Petani ___ padi di sawah.','menanam',['ditanam','penanam','tanaman']],['Bunga itu ___ oleh Dodi kemarin.','ditanam',['menanam','penanam','tanaman']],['Kakak ___ lagu daerah di panggung.','menyanyikan',['dinyanyikan','penyanyi','nyanyian']],['Lagu itu ___ dengan merdu.','dinyanyikan',['menyanyikan','penyanyi','nyanyian']],['Adik ___ pemandangan gunung.','menggambar',['digambar','penggambar','gambaran']],['Anak ayam itu ___ induknya.','mengikuti',['diikuti','pengikut','ikutan']],['Paman ___ ayam di kandang.','memelihara',['dipelihara','pemelihara','peliharaan']],['Kucing itu ___ dengan baik.','dipelihara',['memelihara','pemelihara','peliharaan']],['Nenek ___ bunga setiap sore.','menyiram',['disiram','penyiram','siraman']],['Tanaman itu ___ setiap pagi.','disiram',['menyiram','penyiram','siraman']],['Kami ___ di halaman sekolah.','berkumpul',['dikumpulkan','pengumpul','kumpulan']],['Sampah itu ___ di satu tempat.','dikumpulkan',['berkumpul','pengumpul','kumpulan']],['Adik ___ topi ke sekolah.','memakai',['dipakai','pemakai','pakaian']],['Seragam itu ___ pada hari Senin.','dipakai',['memakai','pemakai','pakaian']],['Kakek ___ ikan di sungai.','memancing',['dipancing','pemancing','pancingan']],['Pak Budi adalah ___ yang sabar.','pemancing',['memancing','dipancing','pancingan']],['Burung itu ___ tinggi di langit.','terbang',['diterbangkan','penerbang','penerbangan']],['Layang-layang itu ___ oleh Andi.','diterbangkan',['terbang','penerbang','penerbangan']],['Ibu ___ nasi goreng untuk kami.','memasak',['dimasak','pemasak','masakan']],['Sayur itu ___ oleh nenek.','dimasak',['memasak','pemasak','masakan']]];
/* [kalimat (kata pertama sudah kapital), satu kata yang seharusnya berhuruf kapital] */
let KAPITAL=[['Ayah pergi ke bandung naik kereta.','bandung'],['Kami mengikuti upacara bendera setiap hari senin.','senin'],['Adik saya lahir pada bulan agustus tahun lalu.','agustus'],['Teman baruku di sekolah itu bernama rina.','rina'],['Kami belajar bahasa indonesia di sekolah.','indonesia'],['Ibu memasak rendang yang khas dari kota padang.','padang'],['Kakak berlibur ke pulau bali bersama keluarga besar.','bali'],['Sungai terpanjang di Kalimantan adalah kapuas.','kapuas'],['Kami mendaki gunung merapi bersama ayah.','merapi'],['Paman saya bekerja di sebuah pabrik di kota surabaya.','surabaya'],['Kami ke rumah nenek pada hari minggu.','minggu'],['Presiden pertama negara Indonesia kita bernama soekarno.','soekarno'],['Kami menonton tarian saman dari Aceh.','saman'],['Ibu saya berasal dari sebuah kota bernama medan.','medan'],['Pelajaran matematika ada pada hari selasa.','selasa'],['Liburan sekolah kami akan dimulai pada bulan juni.','juni'],['Kakakku bernama dita dan adikku Rudi.','dita'],['Ayah membaca koran kompas setiap pagi.','kompas'],['Kami belajar bahasa inggris pada hari Rabu.','inggris'],['Nenek saya tinggal di sebuah desa bernama sukamaju.','sukamaju'],['Pesawat itu terbang tinggi menuju kota jakarta.','jakarta'],['Kami berenang bersama teman di pantai kuta.','kuta'],['Bulan desember adalah bulan terakhir dalam satu tahun.','desember'],['Guru kelas kami di sekolah itu bernama hendra.','hendra'],['Kami menanam pohon pada hari kamis.','kamis'],['Kota yogyakarta sangat terkenal dengan makanan gudeg.','yogyakarta'],['Adik menonton film pada hari sabtu.','sabtu'],['Ibu saya lahir pada tanggal lima bulan maret.','maret'],['Kami mengunjungi museum di kota semarang.','semarang'],['Danau toba berada di Sumatra Utara.','toba']];
/* [peribahasa atau ungkapan, maknanya] — pengecoh diambil dari makna butir lain. */
let PERIBAHASA=[['Besar pasak daripada tiang','Pengeluaran lebih besar daripada pendapatan'],['Ada gula ada semut','Tempat yang menyenangkan banyak didatangi orang'],['Bagai air di daun talas','Orang yang tidak punya pendirian'],['Sedia payung sebelum hujan','Bersiap sebelum terjadi hal yang buruk'],['Tong kosong nyaring bunyinya','Banyak bicara tetapi sedikit ilmunya'],['Air susu dibalas air tuba','Kebaikan dibalas dengan kejahatan'],['Berakit-rakit ke hulu, berenang-renang ke tepian','Bersusah dahulu, bersenang kemudian'],['Malu bertanya sesat di jalan','Kalau tidak mau bertanya akan tersesat'],['Rajin pangkal pandai','Kerajinan membuat orang menjadi pandai'],['Hemat pangkal kaya','Berhemat membuat orang menjadi kaya'],['Bersatu kita teguh, bercerai kita runtuh','Bersatu menjadi kuat, berpecah menjadi lemah'],['Sambil menyelam minum air','Mengerjakan dua hal sekaligus'],['Buah jatuh tidak jauh dari pohonnya','Sifat anak biasanya mirip orang tuanya'],['Seperti katak dalam tempurung','Orang yang sedikit pengetahuannya'],['Panjang tangan','Suka mencuri'],['Ringan tangan','Suka menolong orang lain'],['Buah tangan','Oleh-oleh'],['Naik darah','Menjadi marah'],['Besar kepala','Sombong'],['Rendah hati','Tidak sombong'],['Kutu buku','Orang yang sangat suka membaca'],['Kambing hitam','Orang yang disalahkan padahal tidak bersalah'],['Tangan kanan','Orang kepercayaan'],['Banting tulang','Bekerja keras'],['Angkat kaki','Pergi meninggalkan tempat'],['Gulung tikar','Berhenti berusaha karena bangkrut'],['Buah bibir','Bahan pembicaraan orang banyak'],['Keras kepala','Sulit dinasihati'],['Murah hati','Suka memberi kepada orang lain'],['Cepat kaki ringan tangan','Rajin bekerja dan suka menolong']];
/* [kata, jenis] — jenis: benda | kerja | sifat */
let JENISKATA=[['meja','benda'],['sepeda','benda'],['buku','benda'],['rumah','benda'],['kucing','benda'],['bunga','benda'],['sepatu','benda'],['gelas','benda'],['pohon','benda'],['roti','benda'],['makan','kerja'],['menulis','kerja'],['berlari','kerja'],['membaca','kerja'],['tidur','kerja'],['menyapu','kerja'],['melompat','kerja'],['memasak','kerja'],['menyanyi','kerja'],['minum','kerja'],['tinggi','sifat'],['cantik','sifat'],['rajin','sifat'],['pintar','sifat'],['manis','sifat'],['berani','sifat'],['kotor','sifat'],['cepat','sifat'],['ramah','sifat'],['sedih','sifat']];
const JENIS_LABEL={benda:'Kata Benda',kerja:'Kata Kerja',sifat:'Kata Sifat'};
/* [soal cerita, jawaban berupa angka] — pengecoh angka digenerate di sekitar jawaban. */
let CERITA=[['Ani punya 3 apel. Ibu memberi 2 apel lagi. Berapa apel Ani sekarang?',5],['Budi punya 7 kelereng. Ia memberi 3 kepada adik. Berapa sisa kelereng Budi?',4],['Di kandang ada 4 ayam dan 5 bebek. Berapa jumlah semuanya?',9],['Rina membeli 6 permen, lalu 2 dimakan. Berapa permen yang tersisa?',4],['Ada 8 burung di dahan. 3 burung terbang pergi. Berapa burung yang tinggal?',5],['Ibu membeli 5 jeruk pagi ini dan 4 jeruk sore hari. Berapa jeruk ibu?',9],['Kelas satu punya 10 pensil. 4 pensil dipinjam. Berapa pensil yang ada di kelas?',6],['Andi menanam 2 pohon setiap hari selama 3 hari. Berapa pohon yang ditanam?',6],['Ada 12 kue dibagi sama rata untuk 3 anak. Berapa kue untuk tiap anak?',4],['Di rak ada 3 baris buku. Tiap baris berisi 5 buku. Berapa jumlah bukunya?',15],['Sinta punya 9 balon. 2 balon meletus. Berapa balon Sinta sekarang?',7],['Ayah membeli 2 kotak telur. Tiap kotak berisi 6 telur. Berapa telur semuanya?',12],['Ada 15 murid di kelas. 7 murid perempuan. Berapa murid laki-laki?',8],['Dodi punya 4 kelereng merah dan 6 kelereng biru. Berapa kelereng Dodi?',10],['Nenek memetik 20 mangga, lalu 5 dibagikan. Berapa mangga yang tersisa?',15],['Di taman ada 6 kupu-kupu. Datang 6 kupu-kupu lagi. Berapa semuanya?',12],['Kakak membeli 3 buku seharga 2 ribu tiap buku. Berapa ribu yang dibayar?',6],['Ada 18 kursi disusun jadi 2 baris sama banyak. Berapa kursi tiap baris?',9],['Rudi punya 5 ekor ikan. Ayah memberi 5 ekor lagi. Berapa ikan Rudi?',10],['Ada 14 pensil. 6 pensil patah. Berapa pensil yang masih baik?',8],['Ibu memasak 8 kue. Adik makan 1, kakak makan 2. Berapa kue yang tersisa?',5],['Di kolam ada 7 katak. 4 katak melompat keluar. Berapa katak di kolam?',3],['Setiap hari Andi membaca 3 halaman. Berapa halaman dalam 4 hari?',12],['Ada 16 permen dibagi untuk 4 anak sama banyak. Berapa permen tiap anak?',4],['Rina punya 11 stiker. Ia memberi 5 kepada teman. Berapa sisa stikernya?',6],['Di lapangan ada 9 anak. Datang 8 anak lagi. Berapa anak sekarang?',17],['Paman punya 13 ayam. 4 ayam dijual. Berapa ayam paman sekarang?',9],['Ada 5 meja. Tiap meja ada 4 gelas. Berapa gelas semuanya?',20],['Ibu membeli 10 roti. 3 dimakan pagi, 2 dimakan sore. Berapa sisanya?',5],['Adik punya 6 mobil mainan. Kakak punya 7. Berapa mobil mainan mereka?',13]];
const NUMWORDS=['nol','satu','dua','tiga','empat','lima','enam','tujuh','delapan','sembilan','sepuluh'];
const COUNT_EMO=['🍎','⭐','🐟','🎈','🐝','🍌','🌸','🚗'];
const DEF_CONTENT=JSON.parse(JSON.stringify({huruf:HURUF,suku:SUKU,kalimat:KALIMAT,tanda:TANDA,antonim:ANTONIM,baca:BACA,sinonim:SINONIM,warna:WARNA,katadepan:KATADEPAN,beda:BEDA,baku:BAKU,katatanya:KATATANYA,imbuhan:IMBUHAN,kapital:KAPITAL,peribahasa:PERIBAHASA,jeniskata:JENISKATA,cerita:CERITA}));

function applyContent(c){
  if(!c||typeof c!=='object')return;
  const map={huruf:v=>HURUF=v,suku:v=>SUKU=v,kalimat:v=>KALIMAT=v,tanda:v=>TANDA=v,antonim:v=>ANTONIM=v,baca:v=>BACA=v,sinonim:v=>SINONIM=v,warna:v=>WARNA=v,katadepan:v=>KATADEPAN=v,beda:v=>BEDA=v,baku:v=>BAKU=v,
    katatanya:v=>KATATANYA=v,imbuhan:v=>IMBUHAN=v,kapital:v=>KAPITAL=v,peribahasa:v=>PERIBAHASA=v,jeniskata:v=>JENISKATA=v,cerita:v=>CERITA=v};
  Object.keys(map).forEach(k=>{if(Array.isArray(c[k])&&c[k].length)map[k](c[k]);});
}
function currentContent(){return {huruf:HURUF,suku:SUKU,kalimat:KALIMAT,tanda:TANDA,antonim:ANTONIM,baca:BACA,sinonim:SINONIM,warna:WARNA,katadepan:KATADEPAN,beda:BEDA,baku:BAKU,
  katatanya:KATATANYA,imbuhan:IMBUHAN,kapital:KAPITAL,peribahasa:PERIBAHASA,jeniskata:JENISKATA,cerita:CERITA};}

/* ==================================================== bantuan editor konten */
const CONTENT_HELP={huruf:'Format: [["🍎","apel"], ...] — emoji lalu kata.',suku:'Format: [["⚽","bola",["bo","la"]], ...] — emoji, kata, daftar suku kata.',kalimat:'Format: ["Ibu memasak nasi", ...] — kalimat yang benar urutannya.',tanda:'Format: [["Siapa namamu","?"], ...] — kalimat lalu tanda baca (. ? !).',antonim:'Format: [["besar","kecil"], ...] — kata lalu lawan katanya.',baca:'Format: [{"p":"paragraf","q":[["pertanyaan",["opsi1","opsi2"],0]]}] — 0 = indeks jawaban benar.',sinonim:'Format: [["pintar","pandai"], ...] — kata lalu persamaan katanya.',warna:'Format: [["merah","#e03131"], ...] — nama warna lalu kode warna hex.',katadepan:'Format: [["Buku ada ___ meja","di"], ...] — kalimat (pakai ___) lalu jawaban (di/ke/dari).',beda:'Format: [{"g":["sapi","ayam","kambing"],"odd":"mobil"}, ...] — g = sekelompok, odd = yang berbeda.',baku:'Format: [["apotek","apotik"], ...] — kata baku (jawaban benar) lalu bentuk tidak bakunya.',
  katatanya:'Format: [["___ nama ibumu?","siapa"], ...] — kalimat (pakai ___) lalu kata tanya: apa/siapa/di mana/kapan/mengapa/bagaimana/berapa.',
  imbuhan:'Format: [["Ibu ___ koran.","membaca",["dibaca","pembaca","terbaca"]], ...] — kalimat (pakai ___), jawaban benar, lalu daftar pengecoh.',
  kapital:'Format: [["Ayah pergi ke bandung.","bandung"], ...] — kalimat dengan kata pertama SUDAH kapital, lalu satu kata yang seharusnya kapital.',
  peribahasa:'Format: [["Besar pasak daripada tiang","Pengeluaran lebih besar daripada pendapatan"], ...] — peribahasa/ungkapan lalu maknanya.',
  jeniskata:'Format: [["meja","benda"], ...] — kata lalu jenisnya: benda, kerja, atau sifat.',
  cerita:'Format: [["Ani punya 3 apel, diberi 2 lagi. Berapa?",5], ...] — soal cerita lalu jawaban berupa angka.'};

/* ==================================================== deteksi kemampuan server */
var ONLINE=false,ADMIN_AVAILABLE=false,TTS_AVAILABLE=false;
async function detectCaps(){
  try{
    var r=await fetch('/api/health');var j=await r.json();
    ONLINE=!!j.server;ADMIN_AVAILABLE=!!j.admin;TTS_AVAILABLE=!!j.tts;
  }catch(e){ONLINE=false;ADMIN_AVAILABLE=false;TTS_AVAILABLE=false;}
  return {ONLINE:ONLINE,ADMIN_AVAILABLE:ADMIN_AVAILABLE,TTS_AVAILABLE:TTS_AVAILABLE};
}

/* ==================================================== konten tersimpan */
function storedContent(){try{return JSON.parse(localStorage.getItem(LS_CONTENT)||'{}');}catch(e){return {};}}
function bootContent(){var lc=storedContent();if(lc&&Object.keys(lc).length)applyContent(lc);}
